export const FIND_BOOKS_BY_ID_REQUEST = 'FIND_BOOKS_BY_ID_REQUEST'
export const FIND_BOOKS_BY_ID_SUCCESS = 'FIND_BOOKS_BY_ID_SUCCESS'
export const FIND_BOOKS_BY_ID_FAILURE = 'FIND_BOOKS_BY_ID_FAILURE'

export const FIND_BOOKS_REQUEST = 'FIND_BOOKS_REQUEST'
export const FIND_BOOKS_SUCCESS = 'FIND_BOOKS_SUCCESS'
export const FIND_BOOKS_FAILURE = 'FIND_BOOKS_FAILURE'

export const ADD_BOOK_REQUEST = 'ADD_BOOK_REQUEST'
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS'
export const ADD_BOOK_FAILURE = 'ADD_BOOK_FAILURE'